name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  pull-request:
    name: pull-request
    uses: "{{CENTRAL_REPOSITORY}}/.github/workflows/pull-request.yml@{{CENTRAL_REF}}"
    with:
      capabilities: "{{QUALITY_CAPABILITIES}}"
      environment-manager: "{{ENV_MANAGER}}"
      central-repository: "{{CENTRAL_REPOSITORY}}"
      central-ref: "{{CENTRAL_REF}}"
    permissions:
      contents: read
      pull-requests: read
