name: Super-Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  lint-and-format:
    name: Lint and Auto-format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Super-Linter Configuration
        run: |
          if [ -f .super-linter.env ]; then
            # Export all variables to GITHUB_ENV so they're available in subsequent steps
            grep -v '^#' .super-linter.env | grep '=' | while IFS='=' read -r key value; do
              echo "$key=$value" >> $GITHUB_ENV
            done
            
            # Set language-specific validation variables only if enabled
            echo "Setting super-linter validation variables..."
            if grep -q "ENABLE_JAVASCRIPT=true" .super-linter.env; then
              echo "VALIDATE_JAVASCRIPT_ES=true" >> $GITHUB_ENV
              echo "VALIDATE_JAVASCRIPT_STANDARD=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_TYPESCRIPT=true" .super-linter.env; then
              echo "VALIDATE_TYPESCRIPT_ES=true" >> $GITHUB_ENV
              echo "VALIDATE_TYPESCRIPT_STANDARD=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_PYTHON=true" .super-linter.env; then
              echo "VALIDATE_PYTHON_BLACK=true" >> $GITHUB_ENV
              echo "VALIDATE_PYTHON_PYLINT=true" >> $GITHUB_ENV
              echo "VALIDATE_PYTHON_FLAKE8=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_JAVA=true" .super-linter.env; then
              echo "VALIDATE_JAVA=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_GO=true" .super-linter.env; then
              echo "VALIDATE_GO=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_RUST=true" .super-linter.env; then
              echo "VALIDATE_RUST_2015=true" >> $GITHUB_ENV
              echo "VALIDATE_RUST_2018=true" >> $GITHUB_ENV
              echo "VALIDATE_RUST_2021=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_RUBY=true" .super-linter.env; then
              echo "VALIDATE_RUBY=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_PHP=true" .super-linter.env; then
              echo "VALIDATE_PHP_BUILTIN=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_CSHARP=true" .super-linter.env; then
              echo "VALIDATE_CSHARP=true" >> $GITHUB_ENV
            fi
            if grep -q "ENABLE_CPP=true" .super-linter.env; then
              echo "VALIDATE_CPP=true" >> $GITHUB_ENV
            fi
          fi

      - name: Setup Git Config
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout PR Branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      - name: Run Super-Linter (Auto-fix)
        if: github.event_name == 'pull_request'
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_MODE: true
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: /
          # Language-agnostic linters (always enabled)
          VALIDATE_EDITORCONFIG: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_NATURAL_LANGUAGE: true

      - name: Commit Auto-fixes
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status -s) ]]; then
            git add -A
            git commit -m "chore: auto-fix linting issues [skip ci]" || echo "No changes to commit"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi

      - name: Run Super-Linter (Check Only)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_MODE: false
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          LINTER_RULES_PATH: /
          # Language-agnostic linters (always enabled)
          VALIDATE_EDITORCONFIG: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_NATURAL_LANGUAGE: true
